spring:
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/smoneybagdb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: 
    - classpath*:mapper/*.xml
  type-aliases-package: com.susanna.mvcbeetl.entity    